# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y

# Add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable deep sleep support
CONFIG_ZMK_SLEEP=y

# Improved connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Disable ZMK Studio locking
CONFIG_ZMK_STUDIO_LOCKING=n
